jobs:
  initialize:
    uses: ./.github/workflows/ci_cd_initialize.yml
    with:
      project-name: PROJECT_NAME

  promote-et:
    needs: [ initialize ]
    with:
      environment: et

  promote-qt:
    needs: [ initialize, promote-et ]
    with:
      environment: qt

  promote-dt:
    needs: [ initialize, promote-qt ]
    with:
      environment: dt

  promote-sb:
    needs: [ initialize, promote-dt ]
    with:
      environment: sb

