jobs:
  initialize:
    uses: ./.github/workflows/ci_cd_initialize.yml
    with:
      project-name: PROJECT_NAME

  promote-de:
    needs: [ initialize ]
    with:
      environment: de

  promote-us:
    needs: [ initialize, promote-de ]
    with:
      environment: us

  promote-au:
    needs: [ initialize, promote-us ]
    with:
      environment: au

