jobs:
  initialize:
    uses: ci_cd_initialize.yml
    with:
      project-name: ModuleA
      module: TeamA
  

  promote-de:
    needs: [ initialize ]
    with:
      environment: de
      slack: yoda

  promote-au:
    needs: [ initialize, promote-de ]
    with:
      environment: au
      slack: yoda

  promote-cn:
    needs: [ initialize, promote-au ]
    with:
      environment: cn
      slack: yoda

