jobs:
  initialize:
    uses: ./.github/workflows/ci_cd_initialize.yml
    with:
      project-name: MyProject
      module: Generic-Module

  promote-nb:
    needs: [ initialize ]
    with:
      environment: nb

  promote-sa:
    needs: [ initialize, promote-nb ]
    with:
      environment: sa

