jobs:
  initialize:
    uses: ci_cd_initialize.yml
    with:
      project-name: ModuleD
      module: Generic-Module
  

  promote-nb:
    needs: [ initialize ]
    with:
      environment: nb
      slack: ModuleD-slack-channel

  promote-sa:
    needs: [ initialize, promote-nb ]
    with:
      environment: sa
      slack: ModuleD-slack-channel

