Template should look like this:

jobs:
  initialize:
    uses: ./.github/workflows/ci_cd_initialize.yml
    with:
      project-name: PROJECT_NAME
  repeat for each cluster start:
  promote-<cluster>:
    needs: [ initialize, promote-<previous-cluster>]
    with:
      environment: cluster
  repeat for each cluster end:

Input yml should look like this:
clusters: 
  - et
  - qt


Final Result should look like this:

jobs:
  initialize:
    uses: ./.github/workflows/ci_cd_initialize.yml
    with:
      project-name: PROJECT_NAME

  promote-et:
    needs: [ initialize ]
    with:
      environment: et

  promote-qt:
    needs: [ initialize, promote-et]
    with:
      environment: qt


Generate the final result based on the input yml and the template.